image: node:10

stages:
  - test_ci
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/


test_ci:
  stage: test_ci
  script:
    - yarn install --network-concurrency 1
    - yarn test-ci

release:
  stage: release
  image: kiwicom/curl
  only:
    - master
  script:
   - curl -gX POST $DEPLOY_TRIGGER_URL$CI_COMMIT_SHA


